Feature Enggenerring
---
1. Select features.

2. Extract time-based features.

3. Encode categorical columns.

4. Aggregate transaction-related features for each customer.

5. Normalize/standardaize 

6. Save the final ready file as Final.csv

In [1]:
import sys
import pandas as pd
sys.path.append('../Scripts')
from Feature_engg import TransactionProcessor

df=pd.read_csv('../Data/clean_data.csv')

In [2]:
processor = TransactionProcessor(df)
# processed_df = processor.process_data()

1. Aggregate  Features
---
 Total Transaction Amount: Sum of all transaction amounts for each customer.

○	Average Transaction Amount: Average transaction amount per customer.

○	Transaction Count: Number of transactions per customer.

○	Standard Deviation of Transaction Amounts: Variability of transaction amounts per customer.

In [3]:
# 1. Create Aggregate Features
processor.aggregate_features()

Aggregating features per customer...
Data after aggregation:
          TransactionId         BatchId       AccountId       SubscriptionId  \
0  TransactionId_76871   BatchId_36123  AccountId_3957   SubscriptionId_887
1  TransactionId_73770   BatchId_15642  AccountId_4841  SubscriptionId_3829
2  TransactionId_26203   BatchId_53941  AccountId_4229   SubscriptionId_222
3    TransactionId_380  BatchId_102363   AccountId_648  SubscriptionId_2185
4  TransactionId_28195   BatchId_38780  AccountId_4841  SubscriptionId_3829

        CustomerId CurrencyCode  CountryCode    ProviderId     ProductId  \
0  CustomerId_4406          UGX          256  ProviderId_6  ProductId_10
1  CustomerId_4406          UGX          256  ProviderId_4   ProductId_6
2  CustomerId_4683          UGX          256  ProviderId_6   ProductId_1
3   CustomerId_988          UGX          256  ProviderId_1  ProductId_21
4   CustomerId_988          UGX          256  ProviderId_4   ProductId_6

      ProductCategory    ChannelId    Amount  Value  TransactionStartTime  \
0             airtime  ChannelId_3  6.908755   1000  2018-11-15T02:18:49Z
1  financial_services  ChannelId_2       NaN     25  2018-11-15T02:19:08Z
2             airtime  ChannelId_3  6.216606    500  2018-11-15T02:44:21Z
3        utility_bill  ChannelId_3  9.903538  21800  2018-11-15T03:32:55Z
4  financial_services  ChannelId_2       NaN    644  2018-11-15T03:34:21Z

  PricingStrategy  FraudResult  total_transaction_amount  \
0          Medium            0                471.328497
1          Medium            0                471.328497
2          Medium            0                 12.433212
3          Medium            0                213.353710
4          Medium            0                213.353710

   average_transaction_amount  transaction_count  std_transaction_amount
0                    7.141341                119                1.317315
1                    7.141341                119                1.317315
2                    6.216606                  2                0.000000
3                    8.205912                 38                1.341968
4                    8.205912                 38                1.341968

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,total_transaction_amount,average_transaction_amount,transaction_count,std_transaction_amount
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,6.908755,1000,2018-11-15T02:18:49Z,Medium,0,471.328497,7.141341,119,1.317315
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,NaN,25,2018-11-15T02:19:08Z,Medium,0,471.328497,7.141341,119,1.317315
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,6.216606,500,2018-11-15T02:44:21Z,Medium,0,12.433212,6.216606,2,0.000000
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,9.903538,21800,2018-11-15T03:32:55Z,Medium,0,213.353710,8.205912,38,1.341968
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,NaN,644,2018-11-15T03:34:21Z,Medium,0,213.353710,8.205912,38,1.341968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,NaN,1000,2019-02-13T09:54:09Z,Medium,0,2376.201150,7.665165,573,1.146191
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,6.908755,1000,2019-02-13T09:54:25Z,Medium,0,198.622214,7.356378,43,0.766036
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,NaN,25,2019-02-13T09:54:35Z,Medium,0,198.622214,7.356378,43,0.766036
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,256,ProviderId_6,ProductId_19,tv,ChannelId_3,8.006701,3000,2019-02-13T10:01:10Z,Medium,0,2553.326144,7.295218,524,1.002910
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,NaN,60,2019-02-13T10:01:28Z,Medium,0,2553.326144,7.295218,524,1.002910

2. Extract Features
---

○	Transaction Hour: The hour of the day when the transaction occurred.

○	Transaction Day: The day of the month when the transaction occurred.

○	Transaction Month: The month when the transaction occurred.

○	Transaction Year: The year when the transaction occurred.

In [4]:
# 2. Extract Features
processor.extract_time_features()

Extracting time features...
Data after extracting time features:
          TransactionId         BatchId       AccountId       SubscriptionId  \
0  TransactionId_76871   BatchId_36123  AccountId_3957   SubscriptionId_887
1  TransactionId_73770   BatchId_15642  AccountId_4841  SubscriptionId_3829
2  TransactionId_26203   BatchId_53941  AccountId_4229   SubscriptionId_222
3    TransactionId_380  BatchId_102363   AccountId_648  SubscriptionId_2185
4  TransactionId_28195   BatchId_38780  AccountId_4841  SubscriptionId_3829

        CustomerId CurrencyCode  CountryCode    ProviderId     ProductId  \
0  CustomerId_4406          UGX          256  ProviderId_6  ProductId_10
1  CustomerId_4406          UGX          256  ProviderId_4   ProductId_6
2  CustomerId_4683          UGX          256  ProviderId_6   ProductId_1
3   CustomerId_988          UGX          256  ProviderId_1  ProductId_21
4   CustomerId_988          UGX          256  ProviderId_4   ProductId_6

      ProductCategory  ... PricingStrategy  FraudResult  \
0             airtime  ...          Medium            0
1  financial_services  ...          Medium            0
2             airtime  ...          Medium            0
3        utility_bill  ...          Medium            0
4  financial_services  ...          Medium            0

   total_transaction_amount average_transaction_amount transaction_count  \
0                471.328497                   7.141341               119
1                471.328497                   7.141341               119
2                 12.433212                   6.216606                 2
3                213.353710                   8.205912                38
4                213.353710                   8.205912                38

   std_transaction_amount  transaction_hour  transaction_day  \
0                1.317315                 2               15
1                1.317315                 2               15
2                0.000000                 2               15
3                1.341968                 3               15
4                1.341968                 3               15

   transaction_month  transaction_year
0                 11              2018
1                 11              2018
2                 11              2018
3                 11              2018
4                 11              2018

[5 rows x 24 columns]

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,PricingStrategy,FraudResult,total_transaction_amount,average_transaction_amount,transaction_count,std_transaction_amount,transaction_hour,transaction_day,transaction_month,transaction_year
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,...,Medium,0,471.328497,7.141341,119,1.317315,2,15,11,2018
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,...,Medium,0,471.328497,7.141341,119,1.317315,2,15,11,2018
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,...,Medium,0,12.433212,6.216606,2,0.000000,2,15,11,2018
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,...,Medium,0,213.353710,8.205912,38,1.341968,3,15,11,2018
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,...,Medium,0,213.353710,8.205912,38,1.341968,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,256,ProviderId_4,ProductId_6,financial_services,...,Medium,0,2376.201150,7.665165,573,1.146191,9,13,2,2019
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,256,ProviderId_6,ProductId_10,airtime,...,Medium,0,198.622214,7.356378,43,0.766036,9,13,2,2019
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,256,ProviderId_4,ProductId_6,financial_services,...,Medium,0,198.622214,7.356378,43,0.766036,9,13,2,2019
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,256,ProviderId_6,ProductId_19,tv,...,Medium,0,2553.326144,7.295218,524,1.002910,10,13,2,2019
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,256,ProviderId_4,ProductId_6,financial_services,...,Medium,0,2553.326144,7.295218,524,1.002910,10,13,2,2019

3. Encode Categorical Variables
---
Convert categorical variables into numerical format by using:

"CurrencyCode","CountryCode","ProviderId", "ProductId", "ProductCategor" are selected columns for encoding.

○	One-Hot Encoding: Converts categorical values into binary vectors.

○	Label Encoding: Assigns a unique integer to each category.

In [5]:
# 3. Encode Categorical Columns
processor.encode_categorical_columns()

Encoding categorical columns...
Data after encoding categorical columns:
    CurrencyCode  ProviderId  ProductId  ProductCategory  ChannelId  \
0             0           5          1                0          2
1             0           3         19                2          1
2             0           5          0                0          2
3             0           0         11                8          2
4             0           3         19                2          1

   PricingStrategy
0                2
1                2
2                2
3                2
4                2

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,PricingStrategy,FraudResult,total_transaction_amount,average_transaction_amount,transaction_count,std_transaction_amount,transaction_hour,transaction_day,transaction_month,transaction_year
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,0,256,5,1,0,...,2,0,471.328497,7.141341,119,1.317315,2,15,11,2018
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,0,256,3,19,2,...,2,0,471.328497,7.141341,119,1.317315,2,15,11,2018
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,0,256,5,0,0,...,2,0,12.433212,6.216606,2,0.000000,2,15,11,2018
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,0,256,0,11,8,...,2,0,213.353710,8.205912,38,1.341968,3,15,11,2018
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,0,256,3,19,2,...,2,0,213.353710,8.205912,38,1.341968,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,0,256,3,19,2,...,2,0,2376.201150,7.665165,573,1.146191,9,13,2,2019
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,0,256,5,1,0,...,2,0,198.622214,7.356378,43,0.766036,9,13,2,2019
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,0,256,3,19,2,...,2,0,198.622214,7.356378,43,0.766036,9,13,2,2019
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,0,256,5,8,7,...,2,0,2553.326144,7.295218,524,1.002910,10,13,2,2019
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,0,256,3,19,2,...,2,0,2553.326144,7.295218,524,1.002910,10,13,2,2019

In [6]:

# 4. Handle Missing Values
processor.handle_missing_values()

Handling missing values...
Data after handling missing values:
          TransactionId         BatchId       AccountId       SubscriptionId  \
0  TransactionId_76871   BatchId_36123  AccountId_3957   SubscriptionId_887
1  TransactionId_73770   BatchId_15642  AccountId_4841  SubscriptionId_3829
2  TransactionId_26203   BatchId_53941  AccountId_4229   SubscriptionId_222
3    TransactionId_380  BatchId_102363   AccountId_648  SubscriptionId_2185
4  TransactionId_28195   BatchId_38780  AccountId_4841  SubscriptionId_3829

        CustomerId  CurrencyCode  CountryCode  ProviderId  ProductId  \
0  CustomerId_4406             0          256           5          1
1  CustomerId_4406             0          256           3         19
2  CustomerId_4683             0          256           5          0
3   CustomerId_988             0          256           0         11
4   CustomerId_988             0          256           3         19

   ProductCategory  ...  PricingStrategy  FraudResult  \
0                0  ...                2            0
1                2  ...                2            0
2                0  ...                2            0
3                8  ...                2            0
4                2  ...                2            0

   total_transaction_amount average_transaction_amount  transaction_count  \
0                471.328497                   7.141341                119
1                471.328497                   7.141341                119
2                 12.433212                   6.216606                  2
3                213.353710                   8.205912                 38
4                213.353710                   8.205912                 38

   std_transaction_amount  transaction_hour  transaction_day  \
0                1.317315                 2               15
1                1.317315                 2               15
2                0.000000                 2               15
3                1.341968                 3               15
4                1.341968                 3               15

   transaction_month  transaction_year
0                 11              2018
1                 11              2018
2                 11              2018
3                 11              2018
4                 11              2018

[5 rows x 24 columns]

d:\10 ACADAMY KIFIYA\Week_6\Bati-Bank-Credit-Scoring-Model\notebooks\../Scripts\Feature_engg.py:72: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df[col].fillna(self.df[col].mean(), inplace=True)

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,PricingStrategy,FraudResult,total_transaction_amount,average_transaction_amount,transaction_count,std_transaction_amount,transaction_hour,transaction_day,transaction_month,transaction_year
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,0,256,5,1,0,...,2,0,471.328497,7.141341,119,1.317315,2,15,11,2018
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,0,256,3,19,2,...,2,0,471.328497,7.141341,119,1.317315,2,15,11,2018
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,0,256,5,0,0,...,2,0,12.433212,6.216606,2,0.000000,2,15,11,2018
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,0,256,0,11,8,...,2,0,213.353710,8.205912,38,1.341968,3,15,11,2018
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,0,256,3,19,2,...,2,0,213.353710,8.205912,38,1.341968,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,0,256,3,19,2,...,2,0,2376.201150,7.665165,573,1.146191,9,13,2,2019
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,0,256,5,1,0,...,2,0,198.622214,7.356378,43,0.766036,9,13,2,2019
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,0,256,3,19,2,...,2,0,198.622214,7.356378,43,0.766036,9,13,2,2019
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,0,256,5,8,7,...,2,0,2553.326144,7.295218,524,1.002910,10,13,2,2019
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,0,256,3,19,2,...,2,0,2553.326144,7.295218,524,1.002910,10,13,2,2019

5. Normalize/Standardize Numerical Features
---
Normalization and standardization are scaling techniques used to bring all numerical features onto a similar scale.

○	Normalization: Scales the data to a range of [0, 1].

○	Standardization: Scales the data to have a mean of 0 and a standard deviation of 1.

In [7]:
# 5. Normalize or standardize numerical features (choose either 'normalize' or 'standardize')
processor.normalize_or_standardize(method='normalize')  # or 'standardize'

Applying normalize to numerical columns...
Data after normalize:
      Amount     Value  total_transaction_amount  average_transaction_amount  \
0  0.329065  0.039039                  0.060381                    0.270669
1  0.400290  0.000000                  0.060381                    0.270669
2  0.278573  0.019019                  0.001593                    0.192683
3  0.547532  0.871872                  0.027332                    0.360448
4  0.400290  0.024785                  0.027332                    0.360448

   transaction_count  std_transaction_amount
0           0.028851                0.293691
1           0.028851                0.293691
2           0.000244                0.000000
3           0.009046                0.299187
4           0.009046                0.299187

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,PricingStrategy,FraudResult,total_transaction_amount,average_transaction_amount,transaction_count,std_transaction_amount,transaction_hour,transaction_day,transaction_month,transaction_year
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,0,256,5,1,0,...,2,0,0.060381,0.270669,0.028851,0.293691,2,15,11,2018
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,0,256,3,19,2,...,2,0,0.060381,0.270669,0.028851,0.293691,2,15,11,2018
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,0,256,5,0,0,...,2,0,0.001593,0.192683,0.000244,0.000000,2,15,11,2018
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,0,256,0,11,8,...,2,0,0.027332,0.360448,0.009046,0.299187,3,15,11,2018
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,0,256,3,19,2,...,2,0,0.027332,0.360448,0.009046,0.299187,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,0,256,3,19,2,...,2,0,0.304410,0.314845,0.139853,0.255539,9,13,2,2019
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,0,256,5,1,0,...,2,0,0.025445,0.288804,0.010269,0.170785,9,13,2,2019
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,0,256,3,19,2,...,2,0,0.025445,0.288804,0.010269,0.170785,9,13,2,2019
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,0,256,5,8,7,...,2,0,0.327101,0.283646,0.127873,0.223595,10,13,2,2019
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,0,256,3,19,2,...,2,0,0.327101,0.283646,0.127873,0.223595,10,13,2,2019

In [8]:
processor.save_final_dataframe('../Data/final.csv')

Final DataFrame saved to ../Data/final.csv.